version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0

executors:
  obah-web-executor:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo
  obah-web-deploy:
    docker:
      - image: "circleci/python:2.7"
commands:
  checkout_install:
    description: "Checkout Application Repository"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  test:
    executor: obah-web-executor
    steps:
      - checkout_install
      - run: yarn test

  build:
    executor: obah-web-executor
    steps:
      - checkout_install
      - run: yarn build

  deploy:
    executor: obah-web-deploy
    steps:
      - checkout_install
      - run: yarn build
      - aws-s3/sync:
          from: dist
          to: "s3://obah-web"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
